### ISSUE TITLE
Simple Way

### ISSUE THREAD

**Issue by kaecy** [jacksondm33/BingRewards#7]
Hello, there is a really simple way to do it here.
``` python
cookie = "put your cookie here"
UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299"
MUA = "Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; NOKIA; Lumia 822) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Mobile Safari/537.36 Edge/13.10586"

import urllib2, jsondict

def createRequest(string, ua):
    req = urllib2.Request("https://www.bing.com?q=" + string)
    req.add_header("User-Agent", ua)
    req.add_header("Cookie", cookie)
    return req

jd = jsondict.parse_json_file("words.json")

for word in jd.words:
    urllib2.urlopen(createRequest(word, UA))

for word in jd.mobile_words:
    urllib2.urlopen(createRequest(word, MUA))
```

In your json file you just have a bunch of random words like this:
``` json
{
  "words": [
    "one+piece",
    "facebook",
    "and+so+on"
  ]
}
```
You can get the cookie by logging in to bing and then type document.cookie in a console.

**Comment by jacksondm33** [comment]
Are you saying the cookies stay the same for every login?

Update:
I just checked and verified that it does change. Unless there is a way to keep the same cookie for every login, I don't think this is viable.
The only way I could think of is setting the cookies once and setting them to never expire. This would be like never logging out. I don't know if this would work but it is possible.

**Comment by kaecy** [comment]
I mean the script is simple. 

By the way, how do you login to bing rewards? I'm using the cookie because I don't know how to login.

**Comment by jacksondm33** [comment]
> I mean the script is simple.

I meant that the cookie wouldn't work unless you updated it every time you logged in.

> By the way, how do you login to bing rewards? I'm using the cookie because I don't know how to login.

Are you asking about how to do this on a web browser, or through this script?
Or are you asking how the authentication works?

**Comment by kaecy** [comment]
Actually it (the cookie) is still working. I event logged in and out from the browser and the script works. Never mind about the login. It looks complicated. I'll just keep it simple for now.

**Comment by jacksondm33** [comment]
Are you just copying the cookie from your browser?

**Comment by kaecy** [comment]
Yup.

**Comment by jacksondm33** [comment]
Ok.
The reason this script looks complicated is because it simulates a login every time it runs.
I can add support for using a cookie.

**Comment by jacksondm33** [comment]
I just don't know if that will always work because bing might change something which causes this trick to stop working.
If you use the "Keep me signed in" option, that causes the cookie to never expire which is why I think that it works

**Comment by kaecy** [comment]
I tried to emulate the way you do it but no luck. The WindowsLiveID login page is a script not a html file. I don't know how you're getting the form. Well never mind I've given up.

**Comment by jacksondm33** [comment]
It is pretty complicated and required some time to fully understand and reverse engineer.

**Comment by jacksondm33** [comment]
There are a lot of javascript scripts that normally run in the browser which are hard to read.

**Comment by jacksondm33** [comment]
I added this in #8 
I will merge it once I ensure that it completely works and doesn't cause any side effects.
